### ISSUE TITLE
build_index segfaults without the --k option

### ISSUE THREAD

**Issue by tmaklin** [jnalanko/Themisto#4]
build_index will segfault if the --k option is not given and the index is not loaded with --load-boss option. It would be desirable to quit with an error message since this is the behaviour when the other required arguments are missing.

**Comment by jnalanko** [comment]
There is an assert for this:

        if(!load_boss){
            assert(k != -1);
        }

It looks like asserts do not do anything in the release version. They were enabled in the old Makefile-based build though. I probably should've used some other mechanism for safety checks that are intended to be active in the release version. There are over 100 asserts like this in the codebase. I'll change them so that they throw exceptions instead. Meanwhile you can build the project for yourself so that asserts are included. I don't think it impacts performance much, if at all.

**Comment by jnalanko** [comment]
I changed the asserts in the command line interface to throw exceptions (commit b387b6d). The other asserts are mainly for the tests and for development so they are fine.
